* output.cc : fixed problem in Output and OutputTime constructors,    when output files can not be open
* tests/makefile:
   add common rule test: (tests/makefile) can be included by particulat test makefile
   add %.tst general rule

* some fixes in bin/tests/run_test.sh

* bin/ndiff/ndiff.pl removed debugging messages
* 01, 02, 03 tests - fixed makefiles, ini files , etc. (WIP)

diff --git a/tests/makefile b/tests/makefile
--- a/tests/makefile
+++ b/tests/makefile
@@ -21,18 +21,43 @@
 # $LastChangedDate$
 #
 
+# this file can be included by makefiles from particular tests
+# to use general test: and clean: rules
+
+### rules for tests
+test:
+	../../bin/tests/run_test.sh ${INI_FILES} ${NPROC} ${FLOW_PARAMS}
+
+clean:
+clean:
+	rm -f profiler_*
+	rm -f output/*
+
+### global rules
+
 # Make all tests
-testall: 
-	make -C 01_steady_flow_123d test
-	make -C 02_transport_12d test
+testall: 01.tst 02.tst
+
 
 # Rules for certain tests
-01.tst:
-	make -C 01_steady_flow_123d test
-02.tst:
-	make -C 02_transport_12d test
+#01.tst:
+#	make -C 01_steady_flow_123d test
+#02.tst:
+#	make -C 02_transport_12d test
+
+# general rule to run test given only by number
+%.tst:
+	BASE=$*;\
+	dir="`pwd`/`echo $${BASE}*`";\
+	echo $${dir};\
+	if test -d "$${dir}";\
+	then make -C "$${dir}" test;\
+	else echo "missing test directory $${dir}";\
+	exit 1;\
+	fi
+
 
 # Rule to clean generated files in test directories
-clean:
+cleanall:
 	make -C 01_steady_flow_123d clean
 	make -C 02_transport_12d clean
