Try to fix job aggregation, using GH API

diff --git a/.github/workflows/ci_debug.yaml b/.github/workflows/ci_debug.yaml
--- a/.github/workflows/ci_debug.yaml
+++ b/.github/workflows/ci_debug.yaml
@@ -123,17 +123,7 @@ jobs:
           with:
             name: build_dir
         - run: config/tests/run_with_build_dir.sh make ref-doc
-
-    done:
-        if: ${{always()}}
-        needs: integration_tests
-        runs-on: ubuntu-latest
-        name: Test a job aggregation action.
-        steps:
-          - uses: matrix-org/done-action@v1 # this action succeeds only if all dependent jobs have succeeded
-            with:
-              needs: ${{ toJSON(needs) }}
-        
+                     
         
     conclusion:
         if: ${{always()}}
@@ -145,24 +135,33 @@ jobs:
         
         # continue-on-error jobs always reports sucess to the workflow
         steps:
-        - name: List
-          run: |
-            echo "Integration result: ${{needs.integration_tests.result}}"
-            echo "Integration status: ${{needs.integration_tests.outputs.status}}"
-            echo "Unit result: ${{needs.unit_tests.result}}"
-            echo "Integration status: ${{needs.unit_tests.outputs.status}}"
-            echo "Doc result: ${{needs.build_doc.result}}"
-            echo "Doc status: ${{needs.build_doc.outputs.status}}"
-        - name: Check unit tests 
-          if: needs.unit_tests.outputs.status != 'success'
-          run: exit 1
-        - name: Check integration tests 
-          if: needs.integration_tests.outputs.status != 'success'
-          run: exit 1
-        - name: Check build doc 
-          if: needs.build_doc.outputs.status != 'success'
-          run: exit 1
+          - name: Install gh command
+            run: |
+                sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
+                sudo apt-add-repository https://cli.github.com/packages
+                sudo apt update
+                sudo apt install gh    
+      - name: Check status of all jobs
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          # get the current workflow run ID
+          run_id=$(jq --raw-output .run_id "$GITHUB_EVENT_PATH")
           
+          # get the status of jobs selected by name:
+          #statuses=$(gh api "repos/flow123d/flow123d/actions/runs/4601759611/jobs" --jq '.jobs[] | select(.name | startswith("Integration"))  | .conclusion')
+          
+          # get the status of all jobs
+          statuses=$(gh api "repos/flow123d/flow123d/actions/runs/4601759611/jobs" --jq '.jobs[].conclusion')
+
+          # check if any job has failed
+          if echo "$statuses" | grep -q failure; then
+            echo "One or more jobs have failed"
+            exit 1
+          else
+            echo "All jobs have succeeded"
+          fi    
+
 # steps.xyz.outcome  ... The result before continue-on-error is applied. Possible values: success, failure, cancelled, skipped.
 # steps.xyz.conclusion .. The result after continue-on-error is applied. Always success for continue-on-error.
 # "${{ job.status }}" ?? status of actual job 
