feat(ci): testing concurrency

diff --git a/.github/workflows/ci_debug.yaml b/.github/workflows/ci_debug.yaml
--- a/.github/workflows/ci_debug.yaml
+++ b/.github/workflows/ci_debug.yaml
@@ -178,8 +178,62 @@ jobs:
 
       - name: Build documentation
         run: config/build/run_with_build_dir.sh  dbg_gnu make ref-doc
-                     
+                 
   #conclusion:
+  #  if: ${{always()}}
+  #  runs-on: ubuntu-latest
+  #  name: Workflow conclusion from all job results 
+  #  
+  #  #needs: [integration_tests, unit_tests, build_doc]        
+  #  needs: [build-doc, unit-tests, integration-tests]
+  #  
+  #  # continue-on-error jobs always reports sucess to the workflow
+  #  steps:
+  #    - name: Install gh command
+  #      # Fixed on the last workflow update. Works but seems fragile.
+  #      # But so prooved to be the previous solution:
+  #      # sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
+  #      # sudo apt-add-repository https://cli.github.com/packages
+  #      run: |
+  #          type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
+  #          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
+  #            && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
+  #            && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
+  #            && sudo apt update \
+  #            && sudo apt install gh -y
+  #    - name: Check status of all jobs
+  #      env:
+  #          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  #      run: |
+  #          echo "run_id: ${{ github.run_id }}"
+  #          echo "run_number: ${{ github.run_number }}"
+  #          echo "run_attempt: ${{ github.run_attempt }}"
+  #          
+  #          # get the status of jobs selected by name:
+  #          #statuses=$(gh api "repos/flow123d/flow123d/actions/runs/${run_id}/jobs" --jq '.jobs[] | select(.name startswith("Integration"))  | .conclusion')
+  #          
+  #          # get the status of all jobs
+  #          statuses=$(gh api "repos/flow123d/flow123d/actions/runs/${{ github.run_id }}/jobs" --jq '.jobs[].conclusion')
+  #
+  #          # check if any job has failed
+  #          if echo "$statuses" | grep -q failure; then
+  #              echo "One or more jobs have failed"
+  #              exit 1
+  #          else
+  #              echo "All jobs have succeeded"
+  #          fi    
+
+# steps.xyz.outcome  ... The result before continue-on-error is applied. Possible values: success, failure, cancelled, skipped.
+# steps.xyz.conclusion .. The result after continue-on-error is applied. Always success for continue-on-error.
+# "${{ job.status }}" ?? status of actual job 
+# ${{needs.<job-id>.result}}
+# ${{needs.<job-id>.outpus.<output-id>}} ... does not add the job to needs list automatically !!
+
+# problem is how to integrate the result over the whole job matrix
+# proposed solution: https://github.com/orgs/community/discussions/26822
+# uses `if: ${{always()}}` for the conclusion job which should run the job multiple times
+     
+  #conclusion:concurenccy
   #  if: ${{always()}}
   #  runs-on: ubuntu-latest
   #  name: Workflow conclusion from all job results 
