Fix workflow file

diff --git a/.github/workflows/ci_debug.yaml b/.github/workflows/ci_debug.yaml
--- a/.github/workflows/ci_debug.yaml
+++ b/.github/workflows/ci_debug.yaml
@@ -141,26 +141,26 @@ jobs:
                 sudo apt-add-repository https://cli.github.com/packages
                 sudo apt update
                 sudo apt install gh    
-      - name: Check status of all jobs
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        run: |
-          # get the current workflow run ID
-          run_id=$(jq --raw-output .run_id "$GITHUB_EVENT_PATH")
-          
-          # get the status of jobs selected by name:
-          #statuses=$(gh api "repos/flow123d/flow123d/actions/runs/4601759611/jobs" --jq '.jobs[] | select(.name | startswith("Integration"))  | .conclusion')
-          
-          # get the status of all jobs
-          statuses=$(gh api "repos/flow123d/flow123d/actions/runs/4601759611/jobs" --jq '.jobs[].conclusion')
+          - name: Check status of all jobs
+            env:
+                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+            run: |
+                # get the current workflow run ID
+                run_id=$(jq --raw-output .run_id "$GITHUB_EVENT_PATH")
+                
+                # get the status of jobs selected by name:
+                #statuses=$(gh api "repos/flow123d/flow123d/actions/runs/4601759611/jobs" --jq '.jobs[] | select(.name | startswith("Integration"))  | .conclusion')
+                
+                # get the status of all jobs
+                statuses=$(gh api "repos/flow123d/flow123d/actions/runs/4601759611/jobs" --jq '.jobs[].conclusion')
 
-          # check if any job has failed
-          if echo "$statuses" | grep -q failure; then
-            echo "One or more jobs have failed"
-            exit 1
-          else
-            echo "All jobs have succeeded"
-          fi    
+                # check if any job has failed
+                if echo "$statuses" | grep -q failure; then
+                    echo "One or more jobs have failed"
+                    exit 1
+                else
+                    echo "All jobs have succeeded"
+                fi    
 
 # steps.xyz.outcome  ... The result before continue-on-error is applied. Possible values: success, failure, cancelled, skipped.
 # steps.xyz.conclusion .. The result after continue-on-error is applied. Always success for continue-on-error.
