Fix both debug and release conclusion job

diff --git a/.github/workflows/ci_release.yaml b/.github/workflows/ci_release.yaml
--- a/.github/workflows/ci_release.yaml
+++ b/.github/workflows/ci_release.yaml
@@ -95,7 +95,7 @@ jobs:
         - name: SCP upload to Share
           run: |
             release_tag="${{ steps.vars.outputs.reltag }}"
-            config/package/ssh_upload.sh ${{ steps.vars.outputs.pubdir }} ci-packages/${release_tag} \
+            config/build/ssh_upload.sh ${{ steps.vars.outputs.pubdir }} ci-packages/${release_tag} \
             ${{ secrets.PUBLISH_USER }}@${{ secrets.PUBLISH_HOST }} ${{ secrets.PUBLISH_PASS }}
 
     # Run unit tests with release build, similar to the debug build
@@ -177,3 +177,41 @@ jobs:
           #run: |
             #echo "Job result: ${{job.result}}"
             #echo "Job status: ${{job.status}}"
+
+            
+    conclusion:
+        if: ${{always()}}
+        runs-on: ubuntu-latest
+        name: Workflow conclusion from all job results 
+        
+        #needs: [integration_tests, unit_tests, build_doc]        
+        needs: [packages, unit_tests]
+        
+        # continue-on-error jobs always reports sucess to the workflow
+        steps:
+          - name: Install gh command
+            run: |
+                sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
+                sudo apt-add-repository https://cli.github.com/packages
+                sudo apt update
+                sudo apt install gh    
+          - name: Check status of all jobs
+            env:
+                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+            run: |
+                # get the current workflow run ID
+                run_id=$(jq --raw-output .run_id "$GITHUB_EVENT_PATH")
+                
+                # get the status of jobs selected by name:
+                #statuses=$(gh api "repos/flow123d/flow123d/actions/runs/${run_id}/jobs" --jq '.jobs[] | select(.name startswith("Integration"))  | .conclusion')
+                
+                # get the status of all jobs
+                statuses=$(gh api "repos/flow123d/flow123d/actions/runs/${run_id}/jobs" --jq '.jobs[].conclusion')
+
+                # check if any job has failed
+                if echo "$statuses" | grep -q failure; then
+                    echo "One or more jobs have failed"
+                    exit 1
+                else
+                    echo "All jobs have succeeded"
+                fi    
